server:
  port: 10010
spring:
  application:
    name: api_gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    goods_service: /goods/** #添加商品微服务的路由
    user-service: /user/** #添加用户微服务的路由
    chat_service: /chat/** #添加聊天微服务的路由
    comment_service: /comment/** #添加评论微服务的路由
    community_service: /community/** #添加社区微服务的路由
    feedback_service: /feedback/** #添加用户微服务的路由
    integral_service: /integral/** #添加用户微服务的路由
    order_service: /order/** #添加用户微服务的路由
    auth_service: /auth/** # 授权中心微服务
  add-host-header: true
  sensitive-headers: #全部服务忽略敏感头(全部服务都可以传递cookie)
ribbon:
  ConnectTimeout: 2500 # 连接超时时间(ms)
  ReadTimeout: 20000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
#swagger 配置
#通过网关获取服务地址
swagger:
  butler:
    auto-generate-from-zuul-routes: true
  #配置需要显示swagger接口服务的路由名称
  swagger:
    butler:
      #       generate-routes: goods_service
      generate-routes: goods_service,user-service,chat_service,comment_service,community_service,feedback_service,integral_service,order_service
gomai:
  jwt:
    pubKeyPath: G:\\Study\\专业设计\\rsa\\rsa.pub  # 公钥地址
    cookieName: GM_TOKEN
  filter:   #白名单路径
    allowPaths:
    - /api/auth