server:
  port: 10010
spring:
  application:
    name: api_gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    goods_service: /goods/** #添加商品微服务的路由
    user_service: /user/** #添加用户微服务的路由
    chat_service: /chat/** #添加聊天微服务的路由
    comment_service: /comment/** #添加评论微服务的路由
    community_service: /community/** #添加社区微服务的路由
    feedback_service: /feedback/** #添加用户微服务的路由
    integral_service: /integral/** #添加用户微服务的路由
    order_service: /order/** #添加用户微服务的路由
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms